<?php
$page           = (!empty($_GET['page-id']) && is_numeric($_GET['page-id'])) ? Secure($_GET['page-id']) : 1;
$filter_keyword = (!empty($_GET['query'])) ? Secure($_GET['query']) : '';
$db->pageLimit  = 20;

if (!empty($filter_keyword)) {
    $sql   = "(
    `username`     LIKE '%$filter_keyword%' OR 
    `email`        LIKE '%$filter_keyword%' OR 
    `first_name`   LIKE '%$filter_keyword%' OR 
    `ip_address`   LIKE '%$filter_keyword%' OR 
    `phone_number` LIKE '%$filter_keyword%' OR 
    `last_name`    LIKE '%$filter_keyword%'
  )";

    $mediafiles = $db->orderBy('id', 'DESC')->objectbuilder()->paginate('mediafiles', $page);
}

else {
    $mediafiles = $db->objectbuilder()->orderBy('id', 'DESC')->paginate('mediafiles', $page);
}

if (($page > $db->totalPages) && !empty($_GET['page-id'])) {
    header("Location: " . Wo_LoadAdminLinkSettings('manage-photos'));
    exit();
}

?>
<div class="container-fluid">
    <div class="block-header">
        <h2>Photos > Manage Photos</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage Photos</h2>
                </div>
                    <div class="clearfix"></div>
                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <tbody>
                            <?php
                            foreach ($mediafiles as $mediafilelist) {
                                $wo['mediafilelist'] = $mediafilelist;
                                $wo['mediafilelist']->user = userData($mediafilelist->user_id);
                                echo Wo_LoadAdminPage('manage-photos/list');
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="wo-admincp-feturepager" style="width: 98%;margin: 0 auto;">
                        <div class="pull-left">
                        <span>
                          <?php echo "Showing $page out of " . $db->totalPages; ?>
                        </span>
                        </div>
                        <div class="pull-right">
                            <nav>
                                <ul class="pagination">
                                    <li>
                                        <a href="<?php echo Wo_LoadAdminLinkSettings('manage-photos?page-id=1'); ?>" class="waves-effect" title='First Page'>
                                            <i class="material-icons">first_page</i>
                                        </a>
                                    </li>
                                    <?php if ($page > 1) {  ?>
                                        <li>
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-photos?page-id=' . ($page - 1)); ?>" class="waves-effect" title='Previous Page'>
                                                <i class="material-icons">chevron_left</i>
                                            </a>
                                        </li>
                                    <?php  } ?>

                                    <?php
                                    $nums       = 0;
                                    $nums_pages = ($page > 4) ? ($page - 4) : $page;

                                    for ($i=$nums_pages; $i <= $db->totalPages; $i++) {
                                        if ($nums < 20) {
                                            ?>
                                            <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                                <a href="<?php echo Wo_LoadAdminLinkSettings('manage-photos?page-id=' . ($i)); ?>" class="waves-effect">
                                                    <?php echo $i ?>
                                                </a>
                                            </li>

                                        <?php } $nums++; }?>

                                    <?php if ($db->totalPages > $page) { ?>
                                        <li>
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-photos?page-id=' . ($page + 1)); ?>" class="waves-effect" title="Next Page">
                                                <i class="material-icons">chevron_right</i>
                                            </a>
                                        </li>
                                    <?php } ?>
                                    <li>
                                        <a href="<?php echo Wo_LoadAdminLinkSettings('manage-photos?page-id=' . ($db->totalPages)); ?>" class="waves-effect" title='Last Page'>
                                            <i class="material-icons">last_page</i>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <script>

        function Wo_DeletePhoto(photo_id,photo_file) {
            if (confirm("Are you sure you want to delete this photo?") == false) {
                return false;
            }
            hash_id = '<?php echo Wo_CreateSession();?>';
            $('#PhotoID_' + photo_id).fadeOut(300, function() {
                $(this).remove();
            });
            $.get(Wo_Ajax_Requests_File(),{f:'admin_setting', s:'delete_photo', photo_id: photo_id, photo_file: photo_file, hash_id: hash_id});
        }

    </script>